apiVersion: v1
kind: Secret
metadata:
  name: musicdb-secret
type: Opaque
stringData:
  RDS_USERNAME: dbuser
  RDS_PASSWORD: dbpass
  RDS_HOST: music-api-db.cgksfzkrtzxz.sa-east-1.rds.amazonaws.com
  RDS_PORT: "3306"
  RDS_DATABASE: musicdb